#!/bin/sh

echo "Bloqueando IPs..."
for JAIL in sshd zimbra-admin zimbra-imap zimbra-pop zimbra-smtp zimbra-webmail; do
for IPb in 192.99.113.0/24; do
        fail2ban-client set $JAIL banip $IPb
                done
        done

echo "Desbloqueando IPs..."
for JAIL in sshd zimbra-admin zimbra-imap zimbra-pop zimbra-smtp zimbra-webmail; do
for IPu in 192.168.0.0/23; do
       fail2ban-client set $JAIL unbanip $IPu
                done
        done
