#!/bin/sh

echo "Criando rotinas..."
echo "59 23 * * * root /opt/Bloqueia_IPs_Fail2Ban/cron" > /etc/cron.d/fail2ban

echo "Criando arquivos..."
echo "59 23 * * * root cd /opt/ ; git clone https://github.com/thytetgc/Bloqueia_IPs_Fail2Ban ; /opt/Bloqueia_IPs_Fail2Ban/cron" > /etc/cron.d/fail2ban
cd /opt/ ; git clone https://github.com/thytetgc/Bloqueia_IPs_Fail2Ban ; chmod +x /opt/Bloqueia_IPs_Fail2Ban/cron ; /opt/Bloqueia_IPs_Fail2Ban/cron

# ===================================================================================>

echo "Bloqueando IPs..."
for JAIL in sshd zimbra-admin zimbra-imap zimbra-pop zimbra-smtp zimbra-webmail; do
for IPb in 192.99.113.0/24; do
        fail2ban-client set $JAIL banip $IPb
                done
        done

echo "Desbloqueando IPs..."
for JAIL in sshd zimbra-admin zimbra-imap zimbra-pop zimbra-smtp zimbra-webmail; do
for IPu in 192.168.0.0/23; do
       fail2ban-client set $JAIL unbanip $IPu
                done
        done

# ===================================================================================>
